name: Release

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, windows-latest ]
        include:
        - os: ubuntu-18.04
          asset_name: 'Valve Region Selector *.*.*'
          extension: 'AppImage'

        - os: windows-latest
          asset_name: 'Valve Region Selector *.*.*'
          extension: 'exe'
    steps:
    - name: Check out Git repository
    - uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 15

    - name: Build Electron
      run: |
        npm ci
        npm run dist

    - name: Release
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ github.workspace }}/dist/${{ matrix.asset_name }}.${{ matrix.extension }}
        file_glob: true
        tag: ${{ github.ref }}
